version: '3.7'
services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - db.env
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: